export const ACTION_FILTER = {
    SET_ACTION_FILTER      : "SET_ACTION_FILTER",
}

export const ACTION_USER = {
    SET_ACTION_USER_PROP : "SET_ACTION_USER_PROP",
    SET_ACTION_USER_ADD  : "SET_ACTION_USER_ADD"
}
